# Generated by Django 3.2.13 on 2022-06-30 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/staff')),
                ('dob', models.DateField()),
                ('address_line1', models.CharField(max_length=180)),
                ('address_line2', models.CharField(blank=True, max_length=180, null=True)),
                ('city', models.CharField(max_length=40)),
                ('district_county', models.CharField(max_length=20)),
                ('mobile1', models.CharField(max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
